apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recordings-web.fullname" . }}-patch
  labels:
    {{- include "recordings-web.labels" . | nindent 4 }}
data:
  server.js: {{ .Files.Get "files/server.js" | quote }}
  layout.pug: {{ .Files.Get "files/layout.pug" | quote }}
  camera.pug: {{ .Files.Get "files/camera.pug" | quote }}
  play.pug: {{ .Files.Get "files/play.pug" | quote }}
  connect-youtube.pug: {{ .Files.Get "files/connect-youtube.pug" | quote }}
