{{- if and .Values.basicAuth.enabled (not .Values.basicAuth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recordings-web.fullname" . }}-basic-auth
  labels:
    {{- include "recordings-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  auth: {{ required "basicAuth.htpasswd is required when basicAuth.enabled and no existingSecret" .Values.basicAuth.htpasswd | quote }}
{{- end }}
